SELECT
    FESALIDA,
    SUM(BULTOS_PEDIDOS)     AS BULTOS_PEDIDOS,
    SUM(QSURTIDA)           AS BULTOS_PREPARADOS,
    SUM(BULTOS_SIN_STOCK)   AS BULTOS_SIN_STOCK
FROM COTO.VW_PEDIDOS_SUCURSALES
WHERE FESALIDA = DATE '2026-04-20'
-- opcional:
-- AND XSITSALI IN ('RE','PV','PP')
GROUP BY FESALIDA;