SELECT
    TRUNC(F132.FCREAREG) AS fecha,
    TO_CHAR(F132.FCREAREG, 'HH24:MI:SS') AS hora,
    F132.COPECREA AS operario_id,
    CASE
        WHEN TO_NUMBER(TO_CHAR(F132.FCREAREG, 'HH24')) < 14 THEN 'Mañana'
        WHEN TO_NUMBER(TO_CHAR(F132.FCREAREG, 'HH24')) < 22 THEN 'Tarde'
        ELSE 'Noche'
    END AS turno,
    NULL AS ola_num,
    F602.CNSECTOR AS sector,
    F132.CREFEREN AS sku,
    F132.QCANTIDA AS cantidad_bultos,
    NULL AS tiempo_segundos,
    'ok' AS estado
FROM F132HIST F132
LEFT JOIN F602ASEC F602 
    ON F602.CEMPRESA = F132.CEMPRESA
    AND F602.CALMACEN = F132.CALMACEN
    AND F602.CREFEREN = F132.CREFEREN
WHERE F132.CEMPRESA = '1'
  AND F132.CALMACEN = '93'
  AND F132.CTIPTRAB = 'AU'
  AND F132.CDESCRIP = 'Picking'
AND F132.FCREAREG >= TRUNC(SYSDATE) - 30
ORDER BY F132.FCREAREG DESC;


SELECT * FROM F602ASEC


  SELECT *
     FROM f005ubia A
          JOIN F720DIZO B
             ON     A.CZONALMA = B.CZONALMA
                AND A.CEMPRESA = B.CEMPRESA
                AND A.CALMACEN = B.CALMACEN
          JOIN F802DIVI C
             ON C.CDIVISIO = B.CDIVISIO AND C.CEMPRESA = B.CEMPRESA
          JOIN F681MEUB D
             ON     A.XSITUBIC = D.XSITUBIC
                AND A.CEMPRESA = C.CEMPRESA
                AND D.UBICDEPO = 'S'
          LEFT JOIN WF_GRUPO_ZONAS_LINEAS E
             ON     A.CZONALMA = E.CZONALMA
                AND A.CEMPRESA = E.CEMPRESA
                AND A.CALMACEN = E.CALMACEN
          LEFT JOIN WF_GRUPO_ZONAS F ON E.ID_GRUPO_ZONA = F.ID
          JOIN ML_GRUPOS_CALCULO_DET G ON G.DIVWF = B.CDIVISIO
          JOIN ML_GRUPOS_CALCULO_CAB H ON G.ID_GRUPO = H.ID
    WHERE A.CEMPRESA = '1';
  
  
  SELECT DISTINCT * FROM WF_GRUPO_ZONAS WHERE CZONALMA LIKE '%PE%'